if(NOT DEFINED $ENV{VCPKG_DIR})
    if(CMAKE_HOST_WIN32)
        set(VCPKG_ROOT "D:/library/vcpkg")
    elseif(CMAKE_HOST_UNIX)
        set(VCPKG_ROOT "~/projects/vcpkg")
    endif()
else()
    set(VCPKG_ROOT $ENV{VCPKG_DIR})
endif()

if(DEFINED VCPKG_TARGET_TRIPLET)
  set(VCPKG_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
elseif(NOT DEFINED VCPKG_TARGET_TRIPLET)
    #message(WARNING "need to define VCPKG_TARGET_TRIPLET variabe")
    if(CMAKE_HOST_WIN32)
        set(VCPKG_TARGET_TRIPLET "x64-windows")
    elseif(CMAKE_HOST_UNIX)
        set(VCPKG_TARGET_TRIPLET "x64-linux")
    endif()
        set(VCPKG_DIR "${VCPKG_ROOT}/installed/${VCPKG_TARGET_TRIPLET}")
endif()


if(CMAKE_HOST_WIN32)
    if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        set(CMAKE_TOOLCHAIN_FILE "${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake" CACHE STRING "")
    endif()
    set(DEFAULT_LIBP7_INCLUDE_DIR ${VCPKG_DIR}/include/P7)
elseif(CMAKE_HOST_UNIX)
    #if(NOT DEFINED CMAKE_TOOLCHAIN_FILE)
        if(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
            set(CMAKE_LIBRARY_PATH "${VCPKG_DIR}/debug/lib")
        else()
            set(CMAKE_LIBRARY_PATH "${VCPKG_DIR}/lib")
        endif()
        set(CMAKE_INCLUDE_PATH  "${VCPKG_DIR}/include")
    #endif()
    set(DEFAULT_UNIX_BOOST_DIR "~/projects/library/boost_1_72_0")
    
	set(DEFAULT_UNIX_LIBP7_DIR "~/projects/library/libP7Client")
    set(DEFAULT_LIBP7_INCLUDE_DIR ${DEFAULT_UNIX_LIBP7_DIR}/Headers)
	
	set(OPENSSL_LIBRARY_PATH "/home/user/projects/library/openssl")
    set(OPENSSL_INCLUDE_PATH "/home/user/projects/library/openssl/include")
	
	set(CPPREST_DIR "/home/user/projects/library/casablanca")
	set(CPPREST_INCLUDE_DIR "${CPPREST_DIR}/Release/include")
    set(CPPREST_LIBRARY_DIR "${CPPREST_DIR}/build.debug/Release/Binaries")
    
    set(ACE_ROOT "/projects/ACE_wrappers")
    set(ACE_INCLUDE_DIR ${ACE_ROOT})
    set(ACE_LIBRARY_DIR "${ACE_ROOT}/lib")
	
endif()

#set(DEFAULT_WIN_LOCAL_DIRECTORY "d:/work/local/")
#set(DEFAULT_UNIX_LOCAL_DIRECTORY "/home/user/local/")
